/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: Generated<string>;
}

export interface Member {
  createdAt: Timestamp;
  id: string;
  organizationId: string;
  role: Generated<string>;
  userId: string;
}

export interface Organization {
  createdAt: Timestamp;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string | null;
}

export interface OrganizationRole {
  createdAt: Generated<Timestamp>;
  id: string;
  organizationId: string;
  permission: string | null;
  role: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface RateLimit {
  count: number;
  id: string;
  key: string;
  lastRequest: Int8;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  lastOrganizationId: string | null;
  locale: Generated<string | null>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp | null>;
  value: string;
}

export interface DB {
  account: Account;
  invitation: Invitation;
  member: Member;
  organization: Organization;
  organizationRole: OrganizationRole;
  rateLimit: RateLimit;
  session: Session;
  user: User;
  verification: Verification;
}
